name: CI for PR Merge

on:
  push:
    branches: [ fix-ci ]
  workflow_dispatch: 

jobs:
  macos_build:
    runs-on: macos-11.0
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_test
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  ubuntu_build:
    runs-on: ubuntu-20.04
    env:
      CC: clang
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_test
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  windows_build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_test
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

